Refactor Pyrus task workflows

diff --git a/.github/workflows/add_comment_to_pyrus_task.yml b/.github/workflows/add_comment_to_pyrus_task.yml
--- a/.github/workflows/add_comment_to_pyrus_task.yml
+++ b/.github/workflows/add_comment_to_pyrus_task.yml
@@ -20,17 +20,12 @@ on:
         required: true
 
 jobs:
-  login_to_pyrus:
-    name: Login to Pyrus
-    uses: ./.github/workflows/login_to_pyrus.yml
-    secrets:
-      LOGIN: ${{ secrets.LOGIN }}
-      SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
-
   add_comment_to_pyrus_task:
     name: Add comment to Pyrus task
-    needs: login_to_pyrus
     runs-on: ubuntu-latest
+    env:
+      LOGIN: ${{ secrets.LOGIN }}
+      SECURITY_KEY: ${{ secrets.SECURITY_KEY }}
     steps:
       - name: Check if COMMENT_TEXT is not empty
         run: |
@@ -38,13 +33,36 @@ jobs:
             echo "Comment with Pyrus task link does not exist."
             exit 1
           fi
-      - run: |
+      - name: Authorization with receiving a token
+        id: auth
+        run: |
+          # Authorization with receiving a token
+          response=$(curl -X POST \
+          https://api.pyrus.com/v4/auth \
+          -H 'Content-Type: application/json' \
+          -d '{
+              "login": "'"$LOGIN"'",
+              "security_key": "'"$SECURITY_KEY"'"
+              }'
+           )
+
+          # Check for the absence of 'access_token' field in the response
+          if ! echo "$response" | jq -e '.access_token' > /dev/null; then
+            echo "Error in API request. Response: $response"
+            exit 1
+          else
+            token=$(echo "$response" | jq -r '.access_token')
+            echo "TOKEN=$token" >> $GITHUB_ENV
+            echo "Token received successfully."
+          fi
+      - name: Add comment to Pyrus task
+        id: add_comment
+        run: |
           # Creating a comment in Pyrus task
-          token=${{ needs.login_to_pyrus.outputs.TOKEN }}
           response=$(curl -X POST \
           https://api.pyrus.com/v4/tasks/${{ inputs.TASK_ID }}/comments \
           -H 'Content-Type: application/json' \
-          -H "Authorization: Bearer $token" \
+          -H "Authorization: Bearer $TOKEN" \
           -d '{ "text": "${{ inputs.COMMENT_TEXT }}" }')
 
           # Check for the absence of 'task' field in the response
